version: '3'
services:
  nginx:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./docker/logs:/var/log/nginx
      - ./docker/default.conf:/etc/nginx/conf.d/default.conf
